var GetRandomPerson = function () {
	var rand = Math.random();
	var namesLength = names.length;
	var nameIndex = Math.floor(namesLength * rand);
	return names[nameIndex];
}

var names = [
    "Patrick Pickford",
    "Lonny Lajeunesse",
    "Maria Mumper",
    "Jamaal Jo",
    "Fidel Freshwater",
    "Jesse Jean",
    "Daren Dell",
    "Quinn Quist",
    "Irvin Imes",
    "Isiah Igo",
    "Doug Dunleavy",
    "Gale Gosnell",
    "Ezequiel Estey",
    "Hobert Horvath",
    "Philip Portis",
    "Sergio Sherrell",
    "Shon Simmons",
    "Fausto Folsom",
    "Brock Bibby",
    "Milan Mcneese",
    "Louis Lanterman",
    "Davis Dibernardo",
    "Benjamin Brandon",
    "Jamal Jun",
    "Hubert Hoar",
    "Tony Trantham",
    "Glen Gamble",
    "Antione Abercrombie",
    "Jamison Janousek",
    "Jacinto Jaycox",
    "Emanuel Erskine",
    "Eddy Evitt",
    "Micah Medeiros",
    "Steven Sharber",
    "Royal Riner",
    "Harold Haven",
    "Britt Burchfield",
    "Alexis Altamirano",
    "Zachary Zerangue",
    "Vito Valverde",
    "Jeff Jeanlouis",
    "Donnie Duke",
    "Ferdinand Field",
    "Larry Loisel",
    "Kenneth Kessler",
    "Bert Bigley",
    "Patricia Pulaski",
    "Trenton Tart",
    "Rico Ream",
    "Omer Orduno",
]
