var WordSmith = new function () {
    var crewNames = [
        "Patrick Pickford",
        "Lonny Lajeunesse",
        "Maria Mumper",
        "Jamaal Jo",
        "Fidel Freshwater",
        "Jesse Jean",
        "Daren Dell",
        "Quinn Quist",
        "Irvin Imes",
        "Isiah Igo",
        "Doug Dunleavy",
        "Gale Gosnell",
        "Ezequiel Estey",
        "Hobert Horvath",
        "Philip Portis",
        "Sergio Sherrell",
        "Shon Simmons",
        "Fausto Folsom",
        "Brock Bibby",
        "Milan Mcneese",
        "Louis Lanterman",
        "Davis Dibernardo",
        "Benjamin Brandon",
        "Jamal Jun",
        "Hubert Hoar",
        "Tony Trantham",
        "Glen Gamble",
        "Antione Abercrombie",
        "Jamison Janousek",
        "Jacinto Jaycox",
        "Emanuel Erskine",
        "Eddy Evitt",
        "Micah Medeiros",
        "Steven Sharber",
        "Royal Riner",
        "Harold Haven",
        "Britt Burchfield",
        "Alexis Altamirano",
        "Zachary Zerangue",
        "Vito Valverde",
        "Jeff Jeanlouis",
        "Donnie Duke",
        "Ferdinand Field",
        "Larry Loisel",
        "Kenneth Kessler",
        "Bert Bigley",
        "Patricia Pulaski",
        "Trenton Tart",
        "Rico Ream",
        "Omer Orduno",
    ];
    var pirateNames = [
        "Buccaneer's Servant",
        "Dragon's Madness",
        "Killer's Damned Secret",
        "Night's Doom",
        "Sea's Serpent",
        "The Greedy Eel",
        "The Mad Knave",
        "The Vicious Demon",
        "The Angry Knave",
        "The Bloody Slave",
        "The Coral Doom of Hell",
        "The Coral Insanity",
        "The Cursed Sword",
        "The Dark Grail",
        "The Death of the South",
        "The Hate of the Pirate",
        "The Hell-born Howl",
        "The Horrible Raider of the South",
        "The Horrid Barnacle of the North",
        "The Horror of the North",
        "The Sad Servant",
        "The Screaming Knave",
        "The Shameful Grail",
        "The Shameful Scream",
        "The Vile Dagger",
    ];

    this.getCrewName = function () {
        return crewNames.random ();
    };

    this.getPirateName = function () {
        return pirateNames.random ();
    };
};
